server:
  port: 8084
spring:
  application:
    name: audit-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
